from typing_extensions import Buffer

from winrt.runtime.interop import InterfaceCapsule

def attach_to_window(capsule: InterfaceCapsule, hwnd: int, /) -> None: ...
def get_window_handle(capsule: InterfaceCapsule, /) -> int: ...
def pretranslate_message(capsule: InterfaceCapsule, msg: Buffer, /) -> bool: ...
def get_identity(capsule: InterfaceCapsule, /) -> int: ...
