from typing_extensions import Buffer, CapsuleType

def attach_to_window(capsule: CapsuleType, hwnd: int, /) -> None: ...
def get_window_handle(capsule: CapsuleType, /) -> int: ...
def pretranslate_message(capsule: CapsuleType, msg: Buffer, /) -> bool: ...
def get_identity(capsule: CapsuleType, /) -> int: ...
