// WARNING: Please don't edit this file. It was generated by Python/WinRT v3.2.1

#pragma once

#include "pybase.h"
static_assert(winrt::check_version(PYWINRT_VERSION, "3.2.1"), "Mismatched Py/WinRT headers.");

#include <winrt/Windows.Globalization.PhoneNumberFormatting.h>

namespace py::proj::Windows::Globalization::PhoneNumberFormatting
{
}

namespace py
{
    template<>
    inline constexpr const char* buffer_format<winrt::Windows::Globalization::PhoneNumberFormatting::PhoneNumberFormat> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::Globalization::PhoneNumberFormatting::PhoneNumberMatchResult> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::Globalization::PhoneNumberFormatting::PhoneNumberParseResult> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::Globalization::PhoneNumberFormatting::PredictedPhoneNumberKind> = "i";


    template<>
    struct py_type<winrt::Windows::Globalization::PhoneNumberFormatting::PhoneNumberFormat>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.globalization.phonenumberformatting.PhoneNumberFormat";
        static constexpr const char* module_name = "winrt.windows.globalization.phonenumberformatting";
        static constexpr const char* type_name = "PhoneNumberFormat";
    };

    template<>
    struct py_type<winrt::Windows::Globalization::PhoneNumberFormatting::PhoneNumberMatchResult>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.globalization.phonenumberformatting.PhoneNumberMatchResult";
        static constexpr const char* module_name = "winrt.windows.globalization.phonenumberformatting";
        static constexpr const char* type_name = "PhoneNumberMatchResult";
    };

    template<>
    struct py_type<winrt::Windows::Globalization::PhoneNumberFormatting::PhoneNumberParseResult>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.globalization.phonenumberformatting.PhoneNumberParseResult";
        static constexpr const char* module_name = "winrt.windows.globalization.phonenumberformatting";
        static constexpr const char* type_name = "PhoneNumberParseResult";
    };

    template<>
    struct py_type<winrt::Windows::Globalization::PhoneNumberFormatting::PredictedPhoneNumberKind>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.globalization.phonenumberformatting.PredictedPhoneNumberKind";
        static constexpr const char* module_name = "winrt.windows.globalization.phonenumberformatting";
        static constexpr const char* type_name = "PredictedPhoneNumberKind";
    };

    template<>
    struct py_type<winrt::Windows::Globalization::PhoneNumberFormatting::PhoneNumberFormatter>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.globalization.phonenumberformatting.PhoneNumberFormatter";
        static constexpr const char* module_name = "winrt.windows.globalization.phonenumberformatting";
        static constexpr const char* type_name = "PhoneNumberFormatter";
    };

    template<>
    struct py_type<winrt::Windows::Globalization::PhoneNumberFormatting::PhoneNumberInfo>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.globalization.phonenumberformatting.PhoneNumberInfo";
        static constexpr const char* module_name = "winrt.windows.globalization.phonenumberformatting";
        static constexpr const char* type_name = "PhoneNumberInfo";
    };
}

namespace py::impl::Windows::Globalization::PhoneNumberFormatting
{
}

namespace py::wrapper::Windows::Globalization::PhoneNumberFormatting
{
    using PhoneNumberFormatter = py::winrt_wrapper<winrt::Windows::Globalization::PhoneNumberFormatting::PhoneNumberFormatter>;
    using PhoneNumberInfo = py::winrt_wrapper<winrt::Windows::Globalization::PhoneNumberFormatting::PhoneNumberInfo>;
}

namespace py
{
}
