// WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

#pragma once

#include "pybase.h"
#include <winrt/impl/Windows.Devices.Background.2.h>

namespace py::proj::Windows::Devices::Background
{
}

namespace py
{

    template<>
    struct py_type<winrt::Windows::Devices::Background::DeviceServicingDetails>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.devices.background.DeviceServicingDetails";
        static constexpr const char* module_name = "winrt.windows.devices.background";
        static constexpr const char* type_name = "DeviceServicingDetails";
    };

    template<>
    struct py_type<winrt::Windows::Devices::Background::DeviceUseDetails>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.devices.background.DeviceUseDetails";
        static constexpr const char* module_name = "winrt.windows.devices.background";
        static constexpr const char* type_name = "DeviceUseDetails";
    };
}
