// WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

#pragma once

#include <pywinrt/base.h>

static_assert(
    py::runtime_abi_version_major == 4,
    "this projection needs winrt-runtime headers with ABI major version 4");
static_assert(
    py::runtime_abi_version_minor >= 4,
    "this projection needs winrt-runtime headers with ABI version 4.4 or later");

#if __has_include("py.winrt.guids.h")
#include "py.winrt.guids.h"
#endif

#include "py.Windows.UI.Xaml.Core.Direct.types.h"
#if __has_include("py.Windows.Foundation.types.h")
#include "py.Windows.Foundation.types.h"
#endif
#if __has_include("py.Windows.UI.types.h")
#include "py.Windows.UI.types.h"
#endif
#if __has_include("py.Windows.UI.Xaml.types.h")
#include "py.Windows.UI.Xaml.types.h"
#endif
#if __has_include("py.Windows.UI.Xaml.Media.types.h")
#include "py.Windows.UI.Xaml.Media.types.h"
#endif
#if __has_include("py.Windows.UI.Xaml.Media.Media3D.types.h")
#include "py.Windows.UI.Xaml.Media.Media3D.types.h"
#endif


#include <winrt/Windows.UI.Xaml.Core.Direct.h>

namespace py::impl::Windows::UI::Xaml::Core::Direct
{
}

namespace py::wrapper::Windows::UI::Xaml::Core::Direct
{
    using XamlDirect = py::winrt_wrapper<winrt::Windows::UI::Xaml::Core::Direct::XamlDirect>;
    using IXamlDirectObject = py::winrt_wrapper<winrt::Windows::UI::Xaml::Core::Direct::IXamlDirectObject>;
}

namespace py
{
}
