// WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

#pragma once

#include <pywinrt/base.h>

static_assert(
    py::runtime_abi_version_major == 4,
    "this projection needs winrt-runtime headers with ABI major version 4");
static_assert(
    py::runtime_abi_version_minor >= 4,
    "this projection needs winrt-runtime headers with ABI version 4.4 or later");

#if __has_include("py.winrt.guids.h")
#include "py.winrt.guids.h"
#endif

#include "py.Windows.Devices.Bluetooth.Rfcomm.types.h"
#if __has_include("py.Windows.Devices.Bluetooth.types.h")
#include "py.Windows.Devices.Bluetooth.types.h"
#endif
#if __has_include("py.Windows.Devices.Enumeration.types.h")
#include "py.Windows.Devices.Enumeration.types.h"
#endif
#if __has_include("py.Windows.Foundation.types.h")
#include "py.Windows.Foundation.types.h"
#endif
#if __has_include("py.Windows.Foundation.Collections.types.h")
#include "py.Windows.Foundation.Collections.types.h"
#endif
#if __has_include("py.Windows.Networking.types.h")
#include "py.Windows.Networking.types.h"
#endif
#if __has_include("py.Windows.Networking.Sockets.types.h")
#include "py.Windows.Networking.Sockets.types.h"
#endif
#if __has_include("py.Windows.Storage.Streams.types.h")
#include "py.Windows.Storage.Streams.types.h"
#endif

#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>

#include <winrt/Windows.Devices.Bluetooth.Rfcomm.h>

#if __has_include("py.Windows.Foundation.h")
#include "py.Windows.Foundation.h"
#endif

#if __has_include("py.Windows.Foundation.Collections.h")
#include "py.Windows.Foundation.Collections.h"
#endif

namespace py::impl::Windows::Devices::Bluetooth::Rfcomm
{
}

namespace py::wrapper::Windows::Devices::Bluetooth::Rfcomm
{
    using RfcommDeviceService = py::winrt_wrapper<winrt::Windows::Devices::Bluetooth::Rfcomm::RfcommDeviceService>;
    using RfcommDeviceServicesResult = py::winrt_wrapper<winrt::Windows::Devices::Bluetooth::Rfcomm::RfcommDeviceServicesResult>;
    using RfcommServiceId = py::winrt_wrapper<winrt::Windows::Devices::Bluetooth::Rfcomm::RfcommServiceId>;
    using RfcommServiceProvider = py::winrt_wrapper<winrt::Windows::Devices::Bluetooth::Rfcomm::RfcommServiceProvider>;
}

namespace py
{
}
