// WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

#pragma once

#include "pybase.h"
static_assert(winrt::check_version(PYWINRT_VERSION, "0.0.0"), "Mismatched Py/WinRT headers.");

#include <winrt/Windows.ApplicationModel.Holographic.h>
#include "py.Windows.ApplicationModel.Holographic.types.h"


#if __has_include("py.Windows.Foundation.Numerics.types.h")
#include "py.Windows.Foundation.Numerics.types.h"
#endif

#if __has_include("py.Windows.Perception.Spatial.types.h")
#include "py.Windows.Perception.Spatial.types.h"
#endif

namespace py::impl::Windows::ApplicationModel::Holographic
{
}

namespace py::wrapper::Windows::ApplicationModel::Holographic
{
    using HolographicKeyboard = py::winrt_wrapper<winrt::Windows::ApplicationModel::Holographic::HolographicKeyboard>;
}

namespace py
{
}
