// WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

#pragma once

#include <pywinrt/base.h>

static_assert(
    py::runtime_abi_version_major == 4,
    "this projection needs winrt-runtime headers with ABI major version 4");
static_assert(
    py::runtime_abi_version_minor >= 4,
    "this projection needs winrt-runtime headers with ABI version 4.4 or later");

#if __has_include("py.winrt.guids.h")
#include "py.winrt.guids.h"
#endif

#include "py.Windows.Data.Html.types.h"


#include <winrt/Windows.Data.Html.h>

namespace py::impl::Windows::Data::Html
{
}

namespace py::wrapper::Windows::Data::Html
{
    using HtmlUtilities = py::winrt_wrapper<winrt::Windows::Data::Html::HtmlUtilities>;
}

namespace py
{
}
