// WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

#pragma once

#include "pybase.h"

#if __has_include("py.Windows.Devices.Enumeration.h")
#include "py.Windows.Devices.Enumeration.h"
#endif

#if __has_include("py.Windows.Foundation.h")
#include "py.Windows.Foundation.h"
#endif

#if __has_include("py.Windows.Foundation.Collections.h")
#include "py.Windows.Foundation.Collections.h"
#endif

#if __has_include("py.Windows.Foundation.Numerics.h")
#include "py.Windows.Foundation.Numerics.h"
#endif

#if __has_include("py.Windows.Graphics.Imaging.h")
#include "py.Windows.Graphics.Imaging.h"
#endif

#if __has_include("py.Windows.Media.h")
#include "py.Windows.Media.h"
#endif

#if __has_include("py.Windows.Media.Devices.Core.h")
#include "py.Windows.Media.Devices.Core.h"
#endif

#include <winrt/Windows.Devices.Enumeration.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.Foundation.Numerics.h>
#include <winrt/Windows.Graphics.Imaging.h>
#include <winrt/Windows.Media.h>
#include <winrt/Windows.Media.Devices.Core.h>

#include <winrt/Windows.Devices.Perception.h>

namespace py::proj::Windows::Devices::Perception
{}

namespace py::impl::Windows::Devices::Perception
{}

namespace py::wrapper::Windows::Devices::Perception
{
    using KnownCameraIntrinsicsProperties = py::winrt_wrapper<winrt::Windows::Devices::Perception::KnownCameraIntrinsicsProperties>;
    using KnownPerceptionColorFrameSourceProperties = py::winrt_wrapper<winrt::Windows::Devices::Perception::KnownPerceptionColorFrameSourceProperties>;
    using KnownPerceptionDepthFrameSourceProperties = py::winrt_wrapper<winrt::Windows::Devices::Perception::KnownPerceptionDepthFrameSourceProperties>;
    using KnownPerceptionFrameSourceProperties = py::winrt_wrapper<winrt::Windows::Devices::Perception::KnownPerceptionFrameSourceProperties>;
    using KnownPerceptionInfraredFrameSourceProperties = py::winrt_wrapper<winrt::Windows::Devices::Perception::KnownPerceptionInfraredFrameSourceProperties>;
    using KnownPerceptionVideoFrameSourceProperties = py::winrt_wrapper<winrt::Windows::Devices::Perception::KnownPerceptionVideoFrameSourceProperties>;
    using KnownPerceptionVideoProfileProperties = py::winrt_wrapper<winrt::Windows::Devices::Perception::KnownPerceptionVideoProfileProperties>;
    using PerceptionColorFrame = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionColorFrame>;
    using PerceptionColorFrameArrivedEventArgs = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionColorFrameArrivedEventArgs>;
    using PerceptionColorFrameReader = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionColorFrameReader>;
    using PerceptionColorFrameSource = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionColorFrameSource>;
    using PerceptionColorFrameSourceAddedEventArgs = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionColorFrameSourceAddedEventArgs>;
    using PerceptionColorFrameSourceRemovedEventArgs = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionColorFrameSourceRemovedEventArgs>;
    using PerceptionColorFrameSourceWatcher = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionColorFrameSourceWatcher>;
    using PerceptionControlSession = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionControlSession>;
    using PerceptionDepthCorrelatedCameraIntrinsics = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionDepthCorrelatedCameraIntrinsics>;
    using PerceptionDepthCorrelatedCoordinateMapper = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionDepthCorrelatedCoordinateMapper>;
    using PerceptionDepthFrame = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionDepthFrame>;
    using PerceptionDepthFrameArrivedEventArgs = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionDepthFrameArrivedEventArgs>;
    using PerceptionDepthFrameReader = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionDepthFrameReader>;
    using PerceptionDepthFrameSource = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionDepthFrameSource>;
    using PerceptionDepthFrameSourceAddedEventArgs = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionDepthFrameSourceAddedEventArgs>;
    using PerceptionDepthFrameSourceRemovedEventArgs = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionDepthFrameSourceRemovedEventArgs>;
    using PerceptionDepthFrameSourceWatcher = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionDepthFrameSourceWatcher>;
    using PerceptionFrameSourcePropertiesChangedEventArgs = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionFrameSourcePropertiesChangedEventArgs>;
    using PerceptionFrameSourcePropertyChangeResult = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionFrameSourcePropertyChangeResult>;
    using PerceptionInfraredFrame = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionInfraredFrame>;
    using PerceptionInfraredFrameArrivedEventArgs = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionInfraredFrameArrivedEventArgs>;
    using PerceptionInfraredFrameReader = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionInfraredFrameReader>;
    using PerceptionInfraredFrameSource = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionInfraredFrameSource>;
    using PerceptionInfraredFrameSourceAddedEventArgs = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionInfraredFrameSourceAddedEventArgs>;
    using PerceptionInfraredFrameSourceRemovedEventArgs = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionInfraredFrameSourceRemovedEventArgs>;
    using PerceptionInfraredFrameSourceWatcher = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionInfraredFrameSourceWatcher>;
    using PerceptionVideoProfile = py::winrt_wrapper<winrt::Windows::Devices::Perception::PerceptionVideoProfile>;
}

namespace py
{
    template<>
    inline constexpr const char* buffer_format<winrt::Windows::Devices::Perception::PerceptionFrameSourceAccessStatus> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::Devices::Perception::PerceptionFrameSourcePropertyChangeStatus> = "i";


    template<>
    struct py_type<winrt::Windows::Devices::Perception::PerceptionFrameSourceAccessStatus>
    {
        static PyObject* get_python_type() noexcept;
    };

    template<>
    struct py_type<winrt::Windows::Devices::Perception::PerceptionFrameSourcePropertyChangeStatus>
    {
        static PyObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::KnownCameraIntrinsicsProperties>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::KnownPerceptionColorFrameSourceProperties>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::KnownPerceptionDepthFrameSourceProperties>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::KnownPerceptionFrameSourceProperties>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::KnownPerceptionInfraredFrameSourceProperties>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::KnownPerceptionVideoFrameSourceProperties>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::KnownPerceptionVideoProfileProperties>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionColorFrame>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionColorFrameArrivedEventArgs>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionColorFrameReader>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionColorFrameSource>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionColorFrameSourceAddedEventArgs>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionColorFrameSourceRemovedEventArgs>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionColorFrameSourceWatcher>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionControlSession>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionDepthCorrelatedCameraIntrinsics>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionDepthCorrelatedCoordinateMapper>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionDepthFrame>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionDepthFrameArrivedEventArgs>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionDepthFrameReader>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionDepthFrameSource>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionDepthFrameSourceAddedEventArgs>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionDepthFrameSourceRemovedEventArgs>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionDepthFrameSourceWatcher>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionFrameSourcePropertiesChangedEventArgs>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionFrameSourcePropertyChangeResult>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionInfraredFrame>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionInfraredFrameArrivedEventArgs>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionInfraredFrameReader>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionInfraredFrameSource>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionInfraredFrameSourceAddedEventArgs>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionInfraredFrameSourceRemovedEventArgs>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionInfraredFrameSourceWatcher>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Devices::Perception::PerceptionVideoProfile>
    {
        static PyTypeObject* get_python_type() noexcept;
    };
}
