// WARNING: Please don't edit this file. It was generated by Python/WinRT v2.0.1

#pragma once

#include "pybase.h"
static_assert(winrt::check_version(PYWINRT_VERSION, "2.0.1"), "Mismatched Py/WinRT headers.");

#if __has_include("py.Windows.ApplicationModel.Activation.h")
#include "py.Windows.ApplicationModel.Activation.h"
#endif

#if __has_include("py.Windows.ApplicationModel.Core.h")
#include "py.Windows.ApplicationModel.Core.h"
#endif

#if __has_include("py.Windows.Foundation.h")
#include "py.Windows.Foundation.h"
#endif

#if __has_include("py.Windows.Foundation.Collections.h")
#include "py.Windows.Foundation.Collections.h"
#endif

#if __has_include("py.Windows.Storage.h")
#include "py.Windows.Storage.h"
#endif

#if __has_include("py.Windows.Storage.Streams.h")
#include "py.Windows.Storage.Streams.h"
#endif

#if __has_include("py.Windows.System.h")
#include "py.Windows.System.h"
#endif

#include <winrt/Windows.ApplicationModel.Activation.h>
#include <winrt/Windows.ApplicationModel.Core.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.Storage.h>
#include <winrt/Windows.Storage.Streams.h>
#include <winrt/Windows.System.h>

#include <winrt/Windows.ApplicationModel.h>

namespace py::proj::Windows::ApplicationModel
{}

namespace py::impl::Windows::ApplicationModel
{}

namespace py::wrapper::Windows::ApplicationModel
{
    using AppDisplayInfo = py::winrt_wrapper<winrt::Windows::ApplicationModel::AppDisplayInfo>;
    using AppInfo = py::winrt_wrapper<winrt::Windows::ApplicationModel::AppInfo>;
    using AppInstallerInfo = py::winrt_wrapper<winrt::Windows::ApplicationModel::AppInstallerInfo>;
    using AppInstance = py::winrt_wrapper<winrt::Windows::ApplicationModel::AppInstance>;
    using CameraApplicationManager = py::winrt_wrapper<winrt::Windows::ApplicationModel::CameraApplicationManager>;
    using DesignMode = py::winrt_wrapper<winrt::Windows::ApplicationModel::DesignMode>;
    using EnteredBackgroundEventArgs = py::winrt_wrapper<winrt::Windows::ApplicationModel::EnteredBackgroundEventArgs>;
    using FindRelatedPackagesOptions = py::winrt_wrapper<winrt::Windows::ApplicationModel::FindRelatedPackagesOptions>;
    using FullTrustProcessLaunchResult = py::winrt_wrapper<winrt::Windows::ApplicationModel::FullTrustProcessLaunchResult>;
    using FullTrustProcessLauncher = py::winrt_wrapper<winrt::Windows::ApplicationModel::FullTrustProcessLauncher>;
    using LeavingBackgroundEventArgs = py::winrt_wrapper<winrt::Windows::ApplicationModel::LeavingBackgroundEventArgs>;
    using LimitedAccessFeatureRequestResult = py::winrt_wrapper<winrt::Windows::ApplicationModel::LimitedAccessFeatureRequestResult>;
    using LimitedAccessFeatures = py::winrt_wrapper<winrt::Windows::ApplicationModel::LimitedAccessFeatures>;
    using Package = py::winrt_wrapper<winrt::Windows::ApplicationModel::Package>;
    using PackageCatalog = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageCatalog>;
    using PackageCatalogAddOptionalPackageResult = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageCatalogAddOptionalPackageResult>;
    using PackageCatalogAddResourcePackageResult = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageCatalogAddResourcePackageResult>;
    using PackageCatalogRemoveOptionalPackagesResult = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageCatalogRemoveOptionalPackagesResult>;
    using PackageCatalogRemoveResourcePackagesResult = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageCatalogRemoveResourcePackagesResult>;
    using PackageContentGroup = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageContentGroup>;
    using PackageContentGroupStagingEventArgs = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageContentGroupStagingEventArgs>;
    using PackageId = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageId>;
    using PackageInstallingEventArgs = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageInstallingEventArgs>;
    using PackageStagingEventArgs = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageStagingEventArgs>;
    using PackageStatus = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageStatus>;
    using PackageStatusChangedEventArgs = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageStatusChangedEventArgs>;
    using PackageUninstallingEventArgs = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageUninstallingEventArgs>;
    using PackageUpdateAvailabilityResult = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageUpdateAvailabilityResult>;
    using PackageUpdatingEventArgs = py::winrt_wrapper<winrt::Windows::ApplicationModel::PackageUpdatingEventArgs>;
    using StartupTask = py::winrt_wrapper<winrt::Windows::ApplicationModel::StartupTask>;
    using SuspendingDeferral = py::winrt_wrapper<winrt::Windows::ApplicationModel::SuspendingDeferral>;
    using SuspendingEventArgs = py::winrt_wrapper<winrt::Windows::ApplicationModel::SuspendingEventArgs>;
    using SuspendingOperation = py::winrt_wrapper<winrt::Windows::ApplicationModel::SuspendingOperation>;
    using IEnteredBackgroundEventArgs = py::winrt_wrapper<winrt::Windows::ApplicationModel::IEnteredBackgroundEventArgs>;
    using ILeavingBackgroundEventArgs = py::winrt_wrapper<winrt::Windows::ApplicationModel::ILeavingBackgroundEventArgs>;
    using IPackageCatalogStatics2 = py::winrt_wrapper<winrt::Windows::ApplicationModel::IPackageCatalogStatics2>;
    using ISuspendingDeferral = py::winrt_wrapper<winrt::Windows::ApplicationModel::ISuspendingDeferral>;
    using ISuspendingEventArgs = py::winrt_wrapper<winrt::Windows::ApplicationModel::ISuspendingEventArgs>;
    using ISuspendingOperation = py::winrt_wrapper<winrt::Windows::ApplicationModel::ISuspendingOperation>;
    using PackageInstallProgress = py::winrt_struct_wrapper<winrt::Windows::ApplicationModel::PackageInstallProgress>;
    using PackageVersion = py::winrt_struct_wrapper<winrt::Windows::ApplicationModel::PackageVersion>;
}

namespace py
{
    template<>
    inline constexpr const char* buffer_format<winrt::Windows::ApplicationModel::AddResourcePackageOptions> = "I";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::ApplicationModel::AppExecutionContext> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::ApplicationModel::AppInstallerPolicySource> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::ApplicationModel::FullTrustLaunchResult> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::ApplicationModel::LimitedAccessFeatureStatus> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::ApplicationModel::PackageContentGroupState> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::ApplicationModel::PackageRelationship> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::ApplicationModel::PackageSignatureKind> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::ApplicationModel::PackageUpdateAvailability> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::ApplicationModel::StartupTaskState> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::ApplicationModel::PackageInstallProgress> = "T{I:percent_complete:}";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::ApplicationModel::PackageVersion> = "T{H:major:H:minor:H:build:H:revision:}";


    template<>
    struct py_type<winrt::Windows::ApplicationModel::AddResourcePackageOptions>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "AddResourcePackageOptions";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::AppExecutionContext>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "AppExecutionContext";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::AppInstallerPolicySource>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "AppInstallerPolicySource";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::FullTrustLaunchResult>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "FullTrustLaunchResult";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::LimitedAccessFeatureStatus>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "LimitedAccessFeatureStatus";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageContentGroupState>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageContentGroupState";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageRelationship>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageRelationship";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageSignatureKind>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageSignatureKind";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageUpdateAvailability>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageUpdateAvailability";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::StartupTaskState>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "StartupTaskState";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::AppDisplayInfo>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "AppDisplayInfo";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::AppInfo>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "AppInfo";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::AppInstallerInfo>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "AppInstallerInfo";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::AppInstance>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "AppInstance";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::CameraApplicationManager>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "CameraApplicationManager";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::DesignMode>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "DesignMode";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::EnteredBackgroundEventArgs>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "EnteredBackgroundEventArgs";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::FindRelatedPackagesOptions>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "FindRelatedPackagesOptions";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::FullTrustProcessLaunchResult>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "FullTrustProcessLaunchResult";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::FullTrustProcessLauncher>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "FullTrustProcessLauncher";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::LeavingBackgroundEventArgs>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "LeavingBackgroundEventArgs";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::LimitedAccessFeatureRequestResult>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "LimitedAccessFeatureRequestResult";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::LimitedAccessFeatures>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "LimitedAccessFeatures";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::Package>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "Package";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageCatalog>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageCatalog";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageCatalogAddOptionalPackageResult>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageCatalogAddOptionalPackageResult";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageCatalogAddResourcePackageResult>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageCatalogAddResourcePackageResult";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageCatalogRemoveOptionalPackagesResult>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageCatalogRemoveOptionalPackagesResult";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageCatalogRemoveResourcePackagesResult>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageCatalogRemoveResourcePackagesResult";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageContentGroup>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageContentGroup";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageContentGroupStagingEventArgs>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageContentGroupStagingEventArgs";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageId>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageId";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageInstallingEventArgs>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageInstallingEventArgs";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageStagingEventArgs>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageStagingEventArgs";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageStatus>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageStatus";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageStatusChangedEventArgs>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageStatusChangedEventArgs";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageUninstallingEventArgs>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageUninstallingEventArgs";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageUpdateAvailabilityResult>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageUpdateAvailabilityResult";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageUpdatingEventArgs>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageUpdatingEventArgs";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::StartupTask>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "StartupTask";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::SuspendingDeferral>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "SuspendingDeferral";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::SuspendingEventArgs>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "SuspendingEventArgs";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::SuspendingOperation>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "SuspendingOperation";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::IEnteredBackgroundEventArgs>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "IEnteredBackgroundEventArgs";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::ILeavingBackgroundEventArgs>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "ILeavingBackgroundEventArgs";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::IPackageCatalogStatics2>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "IPackageCatalogStatics2";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::ISuspendingDeferral>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "ISuspendingDeferral";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::ISuspendingEventArgs>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "ISuspendingEventArgs";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::ISuspendingOperation>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "ISuspendingOperation";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageInstallProgress>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageInstallProgress";
    };

    template<>
    struct py_type<winrt::Windows::ApplicationModel::PackageVersion>
    {
        static constexpr const char* module_name = "winrt.windows.applicationmodel";
        static constexpr const char* type_name = "PackageVersion";
    };
}
