// WARNING: Please don't edit this file. It was generated by Python/WinRT v3.2.1

#pragma once

#include "pybase.h"
static_assert(winrt::check_version(PYWINRT_VERSION, "3.2.1"), "Mismatched Py/WinRT headers.");
#include <winrt/Windows.Data.Xml.Dom.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.Security.Credentials.h>

#include <winrt/Windows.Web.Syndication.h>

namespace py::proj::Windows::Web::Syndication
{
}

namespace py
{
    template<>
    inline constexpr const char* buffer_format<winrt::Windows::Web::Syndication::SyndicationErrorStatus> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::Web::Syndication::SyndicationFormat> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::Web::Syndication::SyndicationTextType> = "i";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::Web::Syndication::RetrievalProgress> = "T{I:bytes_retrieved:I:total_bytes_to_retrieve:}";

    template<>
    inline constexpr const char* buffer_format<winrt::Windows::Web::Syndication::TransferProgress> = "T{I:bytes_sent:I:total_bytes_to_send:I:bytes_retrieved:I:total_bytes_to_retrieve:}";


    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationErrorStatus>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationErrorStatus";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationErrorStatus";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationFormat>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationFormat";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationFormat";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationTextType>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationTextType";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationTextType";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationAttribute>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationAttribute";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationAttribute";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationCategory>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationCategory";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationCategory";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationClient>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationClient";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationClient";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationContent>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationContent";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationContent";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationError>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationError";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationError";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationFeed>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationFeed";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationFeed";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationGenerator>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationGenerator";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationGenerator";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationItem>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationItem";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationItem";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationLink>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationLink";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationLink";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationNode>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationNode";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationNode";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationPerson>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationPerson";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationPerson";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::SyndicationText>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.SyndicationText";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "SyndicationText";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::ISyndicationClient>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication._ISyndicationClient";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "_ISyndicationClient";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::ISyndicationNode>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication._ISyndicationNode";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "_ISyndicationNode";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::ISyndicationText>
    {
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication._ISyndicationText";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "_ISyndicationText";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::RetrievalProgress>
    {
        static constexpr std::string_view from_tuple = "winrt._winrt_windows_web_syndication.RetrievalProgress_from_tuple";
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.RetrievalProgress";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "RetrievalProgress";
    };

    template<>
    struct py_type<winrt::Windows::Web::Syndication::TransferProgress>
    {
        static constexpr std::string_view from_tuple = "winrt._winrt_windows_web_syndication.TransferProgress_from_tuple";
        static constexpr std::string_view qualified_name = "winrt.windows.web.syndication.TransferProgress";
        static constexpr const char* module_name = "winrt.windows.web.syndication";
        static constexpr const char* type_name = "TransferProgress";
    };
}

#if __has_include("py.Windows.Data.Xml.Dom.h")
#include "py.Windows.Data.Xml.Dom.h"
#endif

#if __has_include("py.Windows.Foundation.h")
#include "py.Windows.Foundation.h"
#endif

#if __has_include("py.Windows.Foundation.Collections.h")
#include "py.Windows.Foundation.Collections.h"
#endif

#if __has_include("py.Windows.Security.Credentials.h")
#include "py.Windows.Security.Credentials.h"
#endif

namespace py::impl::Windows::Web::Syndication
{
}

namespace py::wrapper::Windows::Web::Syndication
{
    using SyndicationAttribute = py::winrt_wrapper<winrt::Windows::Web::Syndication::SyndicationAttribute>;
    using SyndicationCategory = py::winrt_wrapper<winrt::Windows::Web::Syndication::SyndicationCategory>;
    using SyndicationClient = py::winrt_wrapper<winrt::Windows::Web::Syndication::SyndicationClient>;
    using SyndicationContent = py::winrt_wrapper<winrt::Windows::Web::Syndication::SyndicationContent>;
    using SyndicationError = py::winrt_wrapper<winrt::Windows::Web::Syndication::SyndicationError>;
    using SyndicationFeed = py::winrt_wrapper<winrt::Windows::Web::Syndication::SyndicationFeed>;
    using SyndicationGenerator = py::winrt_wrapper<winrt::Windows::Web::Syndication::SyndicationGenerator>;
    using SyndicationItem = py::winrt_wrapper<winrt::Windows::Web::Syndication::SyndicationItem>;
    using SyndicationLink = py::winrt_wrapper<winrt::Windows::Web::Syndication::SyndicationLink>;
    using SyndicationNode = py::winrt_wrapper<winrt::Windows::Web::Syndication::SyndicationNode>;
    using SyndicationPerson = py::winrt_wrapper<winrt::Windows::Web::Syndication::SyndicationPerson>;
    using SyndicationText = py::winrt_wrapper<winrt::Windows::Web::Syndication::SyndicationText>;
    using ISyndicationClient = py::winrt_wrapper<winrt::Windows::Web::Syndication::ISyndicationClient>;
    using ISyndicationNode = py::winrt_wrapper<winrt::Windows::Web::Syndication::ISyndicationNode>;
    using ISyndicationText = py::winrt_wrapper<winrt::Windows::Web::Syndication::ISyndicationText>;
    using RetrievalProgress = py::winrt_struct_wrapper<winrt::Windows::Web::Syndication::RetrievalProgress>;
    using TransferProgress = py::winrt_struct_wrapper<winrt::Windows::Web::Syndication::TransferProgress>;
}

namespace py
{
}
