from typing_extensions import CapsuleType

def create_direct3d11_device_from_dxgi_device(dxgi_device: int, /) -> CapsuleType: ...
def create_direct3d11_surface_from_dxgi_surface(
    dxgi_surface: int, /
) -> CapsuleType: ...
def get_dxgi_device_from_object(capsule: CapsuleType, /) -> int: ...
def get_dxgi_surface_from_object(capsule: CapsuleType, /) -> int: ...
