from winrt.runtime.interop import InterfaceCapsule

def create_direct3d11_device_from_dxgi_device(
    dxgi_device: int, /
) -> InterfaceCapsule: ...
def create_direct3d11_surface_from_dxgi_surface(
    dxgi_surface: int, /
) -> InterfaceCapsule: ...
def get_dxgi_device_from_object(capsule: InterfaceCapsule, /) -> int: ...
def get_dxgi_surface_from_object(capsule: InterfaceCapsule, /) -> int: ...
