from winui3.microsoft.ui import IconId, DisplayId, WindowId

def get_window_id_from_window(hwnd: int) -> WindowId: ...
def get_window_from_window_id(window_id: WindowId) -> int: ...
def get_display_id_from_monitor(hmonitor: int) -> DisplayId: ...
def get_monitor_from_display_id(display_id: DisplayId) -> int: ...
def get_icon_id_from_icon(hicon: int) -> IconId: ...
def get_icon_from_icon_id(icon_id: IconId) -> int: ...
