def get_window_id_from_window(hwnd: int, /) -> int: ...
def get_window_from_window_id(window_id: int, /) -> int: ...
def get_display_id_from_monitor(hmonitor: int, /) -> int: ...
def get_monitor_from_display_id(display_id: int, /) -> int: ...
def get_icon_id_from_icon(hicon: int, /) -> int: ...
def get_icon_from_icon_id(icon_id: int, /) -> int: ...
