// WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

#include "pybase.h"
#include "py.Windows.UI.Core.Preview.h"


namespace py::cpp::Windows::UI::Core::Preview
{
    struct module_state
    {
        PyTypeObject* type_CoreAppWindowPreview;
        PyTypeObject* type_SystemNavigationCloseRequestedPreviewEventArgs;
        PyTypeObject* type_SystemNavigationManagerPreview;
    };

    // ----- CoreAppWindowPreview class --------------------
    static constexpr const char* const type_name_CoreAppWindowPreview = "CoreAppWindowPreview";

    static PyObject* _new_CoreAppWindowPreview(PyTypeObject* type, PyObject* args, PyObject* kwds) noexcept
    {
        py::set_invalid_activation_error(type_name_CoreAppWindowPreview);
        return nullptr;
    }

    static void _dealloc_CoreAppWindowPreview(py::wrapper::Windows::UI::Core::Preview::CoreAppWindowPreview* self) noexcept
    {
        auto tp = Py_TYPE(self);

        if (PyType_IS_GC(tp))
        {
            PyObject_GC_UnTrack(self);
        }

        std::destroy_at(&self->obj);
        tp->tp_free(self);
        Py_DECREF(tp);
    }

    static PyObject* CoreAppWindowPreview_GetIdFromWindow(PyObject* /*unused*/, PyObject* args) noexcept
    {
        auto arg_count = PyTuple_Size(args);

        if (arg_count == 1)
        {
            if (!winrt::Windows::Foundation::Metadata::ApiInformation::IsMethodPresent(L"Windows.UI.Core.Preview.CoreAppWindowPreview", L"GetIdFromWindow", 1))
            {
                py::set_arg_count_version_error(1);
                return nullptr;
            }

            try
            {
                auto param0 = py::convert_to<winrt::Windows::UI::WindowManagement::AppWindow>(args, 0);

                return py::convert(winrt::Windows::UI::Core::Preview::CoreAppWindowPreview::GetIdFromWindow(param0));
            }
            catch (...)
            {
                py::to_PyErr();
                return nullptr;
            }
        }
        else
        {
            py::set_invalid_arg_count_error(arg_count);
            return nullptr;
        }
    }

    static PyObject* _assign_array_CoreAppWindowPreview(PyObject* /*unused*/, PyObject* arg) noexcept
    {
        auto array = std::make_unique<py::ComArray<winrt::Windows::UI::Core::Preview::CoreAppWindowPreview>>();
        if (!py::cpp::_winrt::Array_Assign(arg, std::move(array)))
        {
            return nullptr;
        }
        Py_RETURN_NONE;
    }

    static PyObject* _from_CoreAppWindowPreview(PyObject* /*unused*/, PyObject* arg) noexcept
    {
        try
        {
            auto return_value = py::convert_to<winrt::Windows::Foundation::IInspectable>(arg);
            return py::convert(return_value.as<winrt::Windows::UI::Core::Preview::CoreAppWindowPreview>());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyMethodDef _methods_CoreAppWindowPreview[] = {
        { "get_id_from_window", reinterpret_cast<PyCFunction>(CoreAppWindowPreview_GetIdFromWindow), METH_VARARGS | METH_STATIC, nullptr },
        { "_assign_array_", _assign_array_CoreAppWindowPreview, METH_O | METH_STATIC, nullptr },
        { "_from", reinterpret_cast<PyCFunction>(_from_CoreAppWindowPreview), METH_O | METH_STATIC, nullptr },
        { }
    };

    static PyGetSetDef _getset_CoreAppWindowPreview[] = {
        { }
    };

    static PyType_Slot _type_slots_CoreAppWindowPreview[] = 
    {
        { Py_tp_new, reinterpret_cast<void*>(_new_CoreAppWindowPreview) },
        { Py_tp_dealloc, reinterpret_cast<void*>(_dealloc_CoreAppWindowPreview) },
        { Py_tp_methods, reinterpret_cast<void*>(_methods_CoreAppWindowPreview) },
        { Py_tp_getset, reinterpret_cast<void*>(_getset_CoreAppWindowPreview) },
        { },
    };

    static PyType_Spec type_spec_CoreAppWindowPreview =
    {
        "_winrt_Windows_UI_Core_Preview.CoreAppWindowPreview",
        sizeof(py::wrapper::Windows::UI::Core::Preview::CoreAppWindowPreview),
        0,
        Py_TPFLAGS_DEFAULT,
        _type_slots_CoreAppWindowPreview
    };

    // ----- SystemNavigationCloseRequestedPreviewEventArgs class --------------------
    static constexpr const char* const type_name_SystemNavigationCloseRequestedPreviewEventArgs = "SystemNavigationCloseRequestedPreviewEventArgs";

    static PyObject* _new_SystemNavigationCloseRequestedPreviewEventArgs(PyTypeObject* type, PyObject* args, PyObject* kwds) noexcept
    {
        py::set_invalid_activation_error(type_name_SystemNavigationCloseRequestedPreviewEventArgs);
        return nullptr;
    }

    static void _dealloc_SystemNavigationCloseRequestedPreviewEventArgs(py::wrapper::Windows::UI::Core::Preview::SystemNavigationCloseRequestedPreviewEventArgs* self) noexcept
    {
        auto tp = Py_TYPE(self);

        if (PyType_IS_GC(tp))
        {
            PyObject_GC_UnTrack(self);
        }

        std::destroy_at(&self->obj);
        tp->tp_free(self);
        Py_DECREF(tp);
    }

    static PyObject* SystemNavigationCloseRequestedPreviewEventArgs_GetDeferral(py::wrapper::Windows::UI::Core::Preview::SystemNavigationCloseRequestedPreviewEventArgs* self, PyObject* args) noexcept
    {
        auto arg_count = PyTuple_Size(args);

        if (arg_count == 0)
        {
            if (!winrt::Windows::Foundation::Metadata::ApiInformation::IsMethodPresent(L"Windows.UI.Core.Preview.SystemNavigationCloseRequestedPreviewEventArgs", L"GetDeferral", 0))
            {
                py::set_arg_count_version_error(0);
                return nullptr;
            }

            try
            {
                return py::convert(self->obj.GetDeferral());
            }
            catch (...)
            {
                py::to_PyErr();
                return nullptr;
            }
        }
        else
        {
            py::set_invalid_arg_count_error(arg_count);
            return nullptr;
        }
    }

    static PyObject* SystemNavigationCloseRequestedPreviewEventArgs_get_Handled(py::wrapper::Windows::UI::Core::Preview::SystemNavigationCloseRequestedPreviewEventArgs* self, void* /*unused*/) noexcept
    {
        if (!winrt::Windows::Foundation::Metadata::ApiInformation::IsPropertyPresent(L"Windows.UI.Core.Preview.SystemNavigationCloseRequestedPreviewEventArgs", L"Handled"))
        {
            PyErr_SetString(PyExc_AttributeError, "property is not available in this version of Windows");
            return nullptr;
        }

        try
        {
            return py::convert(self->obj.Handled());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static int SystemNavigationCloseRequestedPreviewEventArgs_put_Handled(py::wrapper::Windows::UI::Core::Preview::SystemNavigationCloseRequestedPreviewEventArgs* self, PyObject* arg, void* /*unused*/) noexcept
    {
        if (!winrt::Windows::Foundation::Metadata::ApiInformation::IsPropertyPresent(L"Windows.UI.Core.Preview.SystemNavigationCloseRequestedPreviewEventArgs", L"Handled"))
        {
            PyErr_SetString(PyExc_AttributeError, "property is not available in this version of Windows");
            return -1;
        }

        if (arg == nullptr)
        {
            PyErr_SetString(PyExc_AttributeError, "can't delete attribute");
            return -1;
        }

        try
        {
            auto param0 = py::convert_to<bool>(arg);

            self->obj.Handled(param0);
            return 0;
        }
        catch (...)
        {
            py::to_PyErr();
            return -1;
        }
    }

    static PyObject* _assign_array_SystemNavigationCloseRequestedPreviewEventArgs(PyObject* /*unused*/, PyObject* arg) noexcept
    {
        auto array = std::make_unique<py::ComArray<winrt::Windows::UI::Core::Preview::SystemNavigationCloseRequestedPreviewEventArgs>>();
        if (!py::cpp::_winrt::Array_Assign(arg, std::move(array)))
        {
            return nullptr;
        }
        Py_RETURN_NONE;
    }

    static PyObject* _from_SystemNavigationCloseRequestedPreviewEventArgs(PyObject* /*unused*/, PyObject* arg) noexcept
    {
        try
        {
            auto return_value = py::convert_to<winrt::Windows::Foundation::IInspectable>(arg);
            return py::convert(return_value.as<winrt::Windows::UI::Core::Preview::SystemNavigationCloseRequestedPreviewEventArgs>());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyMethodDef _methods_SystemNavigationCloseRequestedPreviewEventArgs[] = {
        { "get_deferral", reinterpret_cast<PyCFunction>(SystemNavigationCloseRequestedPreviewEventArgs_GetDeferral), METH_VARARGS, nullptr },
        { "_assign_array_", _assign_array_SystemNavigationCloseRequestedPreviewEventArgs, METH_O | METH_STATIC, nullptr },
        { "_from", reinterpret_cast<PyCFunction>(_from_SystemNavigationCloseRequestedPreviewEventArgs), METH_O | METH_STATIC, nullptr },
        { }
    };

    static PyGetSetDef _getset_SystemNavigationCloseRequestedPreviewEventArgs[] = {
        { "handled", reinterpret_cast<getter>(SystemNavigationCloseRequestedPreviewEventArgs_get_Handled), reinterpret_cast<setter>(SystemNavigationCloseRequestedPreviewEventArgs_put_Handled), nullptr, nullptr },
        { }
    };

    static PyType_Slot _type_slots_SystemNavigationCloseRequestedPreviewEventArgs[] = 
    {
        { Py_tp_new, reinterpret_cast<void*>(_new_SystemNavigationCloseRequestedPreviewEventArgs) },
        { Py_tp_dealloc, reinterpret_cast<void*>(_dealloc_SystemNavigationCloseRequestedPreviewEventArgs) },
        { Py_tp_methods, reinterpret_cast<void*>(_methods_SystemNavigationCloseRequestedPreviewEventArgs) },
        { Py_tp_getset, reinterpret_cast<void*>(_getset_SystemNavigationCloseRequestedPreviewEventArgs) },
        { },
    };

    static PyType_Spec type_spec_SystemNavigationCloseRequestedPreviewEventArgs =
    {
        "_winrt_Windows_UI_Core_Preview.SystemNavigationCloseRequestedPreviewEventArgs",
        sizeof(py::wrapper::Windows::UI::Core::Preview::SystemNavigationCloseRequestedPreviewEventArgs),
        0,
        Py_TPFLAGS_DEFAULT,
        _type_slots_SystemNavigationCloseRequestedPreviewEventArgs
    };

    // ----- SystemNavigationManagerPreview class --------------------
    static constexpr const char* const type_name_SystemNavigationManagerPreview = "SystemNavigationManagerPreview";

    static PyObject* _new_SystemNavigationManagerPreview(PyTypeObject* type, PyObject* args, PyObject* kwds) noexcept
    {
        py::set_invalid_activation_error(type_name_SystemNavigationManagerPreview);
        return nullptr;
    }

    static void _dealloc_SystemNavigationManagerPreview(py::wrapper::Windows::UI::Core::Preview::SystemNavigationManagerPreview* self) noexcept
    {
        auto tp = Py_TYPE(self);

        if (PyType_IS_GC(tp))
        {
            PyObject_GC_UnTrack(self);
        }

        std::destroy_at(&self->obj);
        tp->tp_free(self);
        Py_DECREF(tp);
    }

    static PyObject* SystemNavigationManagerPreview_GetForCurrentView(PyObject* /*unused*/, PyObject* args) noexcept
    {
        auto arg_count = PyTuple_Size(args);

        if (arg_count == 0)
        {
            if (!winrt::Windows::Foundation::Metadata::ApiInformation::IsMethodPresent(L"Windows.UI.Core.Preview.SystemNavigationManagerPreview", L"GetForCurrentView", 0))
            {
                py::set_arg_count_version_error(0);
                return nullptr;
            }

            try
            {
                return py::convert(winrt::Windows::UI::Core::Preview::SystemNavigationManagerPreview::GetForCurrentView());
            }
            catch (...)
            {
                py::to_PyErr();
                return nullptr;
            }
        }
        else
        {
            py::set_invalid_arg_count_error(arg_count);
            return nullptr;
        }
    }

    static PyObject* SystemNavigationManagerPreview_add_CloseRequested(py::wrapper::Windows::UI::Core::Preview::SystemNavigationManagerPreview* self, PyObject* arg) noexcept
    {
        if (!winrt::Windows::Foundation::Metadata::ApiInformation::IsEventPresent(L"Windows.UI.Core.Preview.SystemNavigationManagerPreview", L"CloseRequested"))
        {
            PyErr_SetString(PyExc_AttributeError, "event is not available in this version of Windows");
            return nullptr;
        }

        try
        {
            auto param0 = py::convert_to<winrt::Windows::Foundation::EventHandler<winrt::Windows::UI::Core::Preview::SystemNavigationCloseRequestedPreviewEventArgs>>(arg);

            return py::convert(self->obj.CloseRequested(param0));
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyObject* SystemNavigationManagerPreview_remove_CloseRequested(py::wrapper::Windows::UI::Core::Preview::SystemNavigationManagerPreview* self, PyObject* arg) noexcept
    {
        if (!winrt::Windows::Foundation::Metadata::ApiInformation::IsEventPresent(L"Windows.UI.Core.Preview.SystemNavigationManagerPreview", L"CloseRequested"))
        {
            PyErr_SetString(PyExc_AttributeError, "event is not available in this version of Windows");
            return nullptr;
        }

        try
        {
            auto param0 = py::convert_to<winrt::event_token>(arg);

            self->obj.CloseRequested(param0);
            Py_RETURN_NONE;
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyObject* _assign_array_SystemNavigationManagerPreview(PyObject* /*unused*/, PyObject* arg) noexcept
    {
        auto array = std::make_unique<py::ComArray<winrt::Windows::UI::Core::Preview::SystemNavigationManagerPreview>>();
        if (!py::cpp::_winrt::Array_Assign(arg, std::move(array)))
        {
            return nullptr;
        }
        Py_RETURN_NONE;
    }

    static PyObject* _from_SystemNavigationManagerPreview(PyObject* /*unused*/, PyObject* arg) noexcept
    {
        try
        {
            auto return_value = py::convert_to<winrt::Windows::Foundation::IInspectable>(arg);
            return py::convert(return_value.as<winrt::Windows::UI::Core::Preview::SystemNavigationManagerPreview>());
        }
        catch (...)
        {
            py::to_PyErr();
            return nullptr;
        }
    }

    static PyMethodDef _methods_SystemNavigationManagerPreview[] = {
        { "get_for_current_view", reinterpret_cast<PyCFunction>(SystemNavigationManagerPreview_GetForCurrentView), METH_VARARGS | METH_STATIC, nullptr },
        { "add_close_requested", reinterpret_cast<PyCFunction>(SystemNavigationManagerPreview_add_CloseRequested), METH_O, nullptr },
        { "remove_close_requested", reinterpret_cast<PyCFunction>(SystemNavigationManagerPreview_remove_CloseRequested), METH_O, nullptr },
        { "_assign_array_", _assign_array_SystemNavigationManagerPreview, METH_O | METH_STATIC, nullptr },
        { "_from", reinterpret_cast<PyCFunction>(_from_SystemNavigationManagerPreview), METH_O | METH_STATIC, nullptr },
        { }
    };

    static PyGetSetDef _getset_SystemNavigationManagerPreview[] = {
        { }
    };

    static PyType_Slot _type_slots_SystemNavigationManagerPreview[] = 
    {
        { Py_tp_new, reinterpret_cast<void*>(_new_SystemNavigationManagerPreview) },
        { Py_tp_dealloc, reinterpret_cast<void*>(_dealloc_SystemNavigationManagerPreview) },
        { Py_tp_methods, reinterpret_cast<void*>(_methods_SystemNavigationManagerPreview) },
        { Py_tp_getset, reinterpret_cast<void*>(_getset_SystemNavigationManagerPreview) },
        { },
    };

    static PyType_Spec type_spec_SystemNavigationManagerPreview =
    {
        "_winrt_Windows_UI_Core_Preview.SystemNavigationManagerPreview",
        sizeof(py::wrapper::Windows::UI::Core::Preview::SystemNavigationManagerPreview),
        0,
        Py_TPFLAGS_DEFAULT,
        _type_slots_SystemNavigationManagerPreview
    };

    // ----- Windows.UI.Core.Preview Initialization --------------------
    PyDoc_STRVAR(module_doc, "Windows::UI::Core::Preview");

    static PyMethodDef module_methods[] = {
        {}};


    static int module_traverse(PyObject* module, visitproc visit, void* arg) noexcept
    {
        auto state = reinterpret_cast<module_state*>(PyModule_GetState(module));

        if (!state)
        {
            return 0;
        }

        Py_VISIT(state->type_CoreAppWindowPreview);
        Py_VISIT(state->type_SystemNavigationCloseRequestedPreviewEventArgs);
        Py_VISIT(state->type_SystemNavigationManagerPreview);

        return 0;
    }

    static int module_clear(PyObject* module) noexcept
    {
        auto state = reinterpret_cast<module_state*>(PyModule_GetState(module));

        if (!state)
        {
            return 0;
        }

        Py_CLEAR(state->type_CoreAppWindowPreview);
        Py_CLEAR(state->type_SystemNavigationCloseRequestedPreviewEventArgs);
        Py_CLEAR(state->type_SystemNavigationManagerPreview);

        return 0;
    }


    static PyModuleDef module_def
        = {PyModuleDef_HEAD_INIT,
           "_winrt_Windows_UI_Core_Preview",
           module_doc,
           sizeof(module_state),
           module_methods,
           nullptr,
           module_traverse,
           module_clear,
           nullptr};

} // py::cpp::Windows::UI::Core::Preview

PyMODINIT_FUNC PyInit__winrt_Windows_UI_Core_Preview(void) noexcept
{
    using namespace py::cpp::Windows::UI::Core::Preview;

    py::pyobj_handle module{PyModule_Create(&module_def)};

    if (!module)
    {
        return nullptr;
    }

    auto object_type = py::get_python_type<py::Object>();
    if (!object_type)
    {
        return nullptr;
    }

    py::pyobj_handle object_bases{PyTuple_Pack(1, object_type)};

    if (!object_bases)
    {
        return nullptr;
    }

    auto state = reinterpret_cast<module_state*>(PyModule_GetState(module.get()));
    WINRT_ASSERT(state);

    state->type_CoreAppWindowPreview = py::register_python_type(module.get(), type_name_CoreAppWindowPreview, &type_spec_CoreAppWindowPreview, object_bases.get(), nullptr);
    if (!state->type_CoreAppWindowPreview)
    {
        return nullptr;
    }

    state->type_SystemNavigationCloseRequestedPreviewEventArgs = py::register_python_type(module.get(), type_name_SystemNavigationCloseRequestedPreviewEventArgs, &type_spec_SystemNavigationCloseRequestedPreviewEventArgs, object_bases.get(), nullptr);
    if (!state->type_SystemNavigationCloseRequestedPreviewEventArgs)
    {
        return nullptr;
    }

    state->type_SystemNavigationManagerPreview = py::register_python_type(module.get(), type_name_SystemNavigationManagerPreview, &type_spec_SystemNavigationManagerPreview, object_bases.get(), nullptr);
    if (!state->type_SystemNavigationManagerPreview)
    {
        return nullptr;
    }


    return module.detach();
}

PyTypeObject* py::winrt_type<winrt::Windows::UI::Core::Preview::CoreAppWindowPreview>::get_python_type() noexcept {
    using namespace py::cpp::Windows::UI::Core::Preview;

    PyObject* module = PyState_FindModule(&module_def);

    if (!module) {
        PyErr_SetString(PyExc_RuntimeError, "could not find module for Windows::UI::Core::Preview");
        return nullptr;
    }

    auto state = reinterpret_cast<module_state*>(PyModule_GetState(module));
    assert(state);

    auto python_type = state->type_CoreAppWindowPreview;

    if (!python_type) {
        PyErr_SetString(PyExc_RuntimeError, "type winrt::Windows::UI::Core::Preview::CoreAppWindowPreview is not registered");
        return nullptr;
    }

    return python_type;
}

PyTypeObject* py::winrt_type<winrt::Windows::UI::Core::Preview::SystemNavigationCloseRequestedPreviewEventArgs>::get_python_type() noexcept {
    using namespace py::cpp::Windows::UI::Core::Preview;

    PyObject* module = PyState_FindModule(&module_def);

    if (!module) {
        PyErr_SetString(PyExc_RuntimeError, "could not find module for Windows::UI::Core::Preview");
        return nullptr;
    }

    auto state = reinterpret_cast<module_state*>(PyModule_GetState(module));
    assert(state);

    auto python_type = state->type_SystemNavigationCloseRequestedPreviewEventArgs;

    if (!python_type) {
        PyErr_SetString(PyExc_RuntimeError, "type winrt::Windows::UI::Core::Preview::SystemNavigationCloseRequestedPreviewEventArgs is not registered");
        return nullptr;
    }

    return python_type;
}

PyTypeObject* py::winrt_type<winrt::Windows::UI::Core::Preview::SystemNavigationManagerPreview>::get_python_type() noexcept {
    using namespace py::cpp::Windows::UI::Core::Preview;

    PyObject* module = PyState_FindModule(&module_def);

    if (!module) {
        PyErr_SetString(PyExc_RuntimeError, "could not find module for Windows::UI::Core::Preview");
        return nullptr;
    }

    auto state = reinterpret_cast<module_state*>(PyModule_GetState(module));
    assert(state);

    auto python_type = state->type_SystemNavigationManagerPreview;

    if (!python_type) {
        PyErr_SetString(PyExc_RuntimeError, "type winrt::Windows::UI::Core::Preview::SystemNavigationManagerPreview is not registered");
        return nullptr;
    }

    return python_type;
}
