# WARNING: Please don't edit this file. It was generated by Python/WinRT v3.0.0

import datetime
import sys
import types
import typing
import uuid as _uuid
from builtins import property as _property

import winrt._winrt
import winrt.system
import winrt.windows.foundation as windows_foundation
import winrt.windows.ui.windowmanagement as windows_ui_windowmanagement

Self = typing.TypeVar('Self')

@typing.final
class WindowManagementPreview_Static(winrt._winrt.IInspectable_Static):
    # System.Void Windows.UI.WindowManagement.Preview.WindowManagementPreview::SetPreferredMinSize(Windows.UI.WindowManagement.AppWindow,Windows.Foundation.Size)
    def set_preferred_min_size(cls, window: windows_ui_windowmanagement.AppWindow, preferred_frame_min_size: typing.Union[windows_foundation.Size, typing.Tuple[winrt.system.Single, winrt.system.Single]], /) -> None: ...

@typing.final
class WindowManagementPreview(winrt.system.Object, metaclass=WindowManagementPreview_Static):
    pass

