# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import datetime
import sys
import types
import typing
import uuid as _uuid
from builtins import property as _property

import winrt.system

Self = typing.TypeVar('Self')

class SystemProtection(winrt.system.Object):
    @staticmethod
    def _from(obj: winrt.system.Object, /) -> SystemProtection: ...
    @staticmethod
    def request_screen_unlock() -> None: ...
    screen_locked: typing.ClassVar[bool]

