from ..... import _winrt_windows_graphics_capture_interop

create_for_monitor = _winrt_windows_graphics_capture_interop.create_for_monitor
create_for_window = _winrt_windows_graphics_capture_interop.create_for_window
