# WARNING: Please don't edit this file. It was generated by Python/WinRT v2.0.0-beta.2

import enum

import winrt.system
from winrt import _winrt_windows_devices_haptics

__all__ = [
    "VibrationAccessStatus",
    "KnownSimpleHapticsControllerWaveforms",
    "SimpleHapticsController",
    "SimpleHapticsControllerFeedback",
    "VibrationDevice",
]

class VibrationAccessStatus(enum.IntEnum):
    ALLOWED = 0
    DENIED_BY_USER = 1
    DENIED_BY_SYSTEM = 2
    DENIED_BY_ENERGY_SAVER = 3

KnownSimpleHapticsControllerWaveforms = _winrt_windows_devices_haptics.KnownSimpleHapticsControllerWaveforms
SimpleHapticsController = _winrt_windows_devices_haptics.SimpleHapticsController
SimpleHapticsControllerFeedback = _winrt_windows_devices_haptics.SimpleHapticsControllerFeedback
VibrationDevice = _winrt_windows_devices_haptics.VibrationDevice
