# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import winrt.system

_ns_module = winrt.system._import_ns_module("Windows.ApplicationModel.Payments.Provider")

try:
    import winrt.windows.applicationmodel.payments
except ImportError:
    pass

try:
    import winrt.windows.foundation
except ImportError:
    pass

try:
    import winrt.windows.foundation.collections
except ImportError:
    pass


PaymentAppCanMakePaymentTriggerDetails = _ns_module.PaymentAppCanMakePaymentTriggerDetails
PaymentAppManager = _ns_module.PaymentAppManager
PaymentTransaction = _ns_module.PaymentTransaction
PaymentTransactionAcceptResult = _ns_module.PaymentTransactionAcceptResult
