# WARNING: Please don't edit this file. It was generated by Python/WinRT v3.2.1

import datetime
import sys
import types
import typing
import uuid as _uuid
from builtins import property as _property

import winrt._winrt
import winrt.system
import winrt.windows.devices.geolocation as windows_devices_geolocation
import winrt.windows.foundation as windows_foundation

from winrt.windows.devices.geolocation.provider import LocationOverrideStatus

Self = typing.TypeVar('Self')

@typing.final
class GeolocationProvider(winrt.system.Object):
    def __new__(cls: typing.Type[Self]) -> Self: ...
    # System.Void Windows.Devices.Geolocation.Provider.GeolocationProvider::ClearOverridePosition()
    def clear_override_position(self) -> None: ...
    # Windows.Devices.Geolocation.Provider.LocationOverrideStatus Windows.Devices.Geolocation.Provider.GeolocationProvider::SetOverridePosition(Windows.Devices.Geolocation.BasicGeoposition,Windows.Devices.Geolocation.PositionSource,System.Double)
    def set_override_position(self, new_position: typing.Union[windows_devices_geolocation.BasicGeoposition, typing.Tuple[winrt.system.Double, winrt.system.Double, winrt.system.Double]], position_source: windows_devices_geolocation.PositionSource, accuracy_in_meters: winrt.system.Double, /) -> LocationOverrideStatus: ...
    # Windows.Foundation.EventRegistrationToken Windows.Devices.Geolocation.Provider.GeolocationProvider::add_IsOverriddenChanged(Windows.Foundation.EventHandler`1<System.Object>)
    def add_is_overridden_changed(self, handler: windows_foundation.EventHandler[winrt.system.Object], /) -> windows_foundation.EventRegistrationToken: ...
    # System.Void Windows.Devices.Geolocation.Provider.GeolocationProvider::remove_IsOverriddenChanged(Windows.Foundation.EventRegistrationToken)
    def remove_is_overridden_changed(self, token: typing.Union[windows_foundation.EventRegistrationToken, typing.Tuple[winrt.system.Int64]], /) -> None: ...
    # System.Boolean Windows.Devices.Geolocation.Provider.GeolocationProvider::get_IsOverridden()
    @_property
    def is_overridden(self) -> bool: ...

