
MTA: int
STA: int

def init_apartment(apartment_type: int) -> None: ...
def uninit_apartment() -> None: ...
def initialize_with_window(obj: winrt_base, hwnd: int) -> None: ...

class winrt_base:
    ...
