// WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

#pragma once

#include "pybase.h"
static_assert(winrt::check_version(PYWINRT_VERSION, "0.0.0"), "Mismatched Py/WinRT headers.");

#include <winrt/Microsoft.UI.Text.h>
#include "py.Microsoft.UI.Text.types.h"


#if __has_include("py.Windows.Foundation.types.h")
#include "py.Windows.Foundation.types.h"
#endif

#if __has_include("py.Windows.Storage.Streams.types.h")
#include "py.Windows.Storage.Streams.types.h"
#endif

#if __has_include("py.Windows.UI.types.h")
#include "py.Windows.UI.types.h"
#endif

#if __has_include("py.Windows.UI.Text.types.h")
#include "py.Windows.UI.Text.types.h"
#endif

namespace py::impl::Microsoft::UI::Text
{
}

namespace py::wrapper::Microsoft::UI::Text
{
    using FontWeights = py::winrt_wrapper<winrt::Microsoft::UI::Text::FontWeights>;
    using RichEditTextDocument = py::winrt_wrapper<winrt::Microsoft::UI::Text::RichEditTextDocument>;
    using RichEditTextRange = py::winrt_wrapper<winrt::Microsoft::UI::Text::RichEditTextRange>;
    using TextConstants = py::winrt_wrapper<winrt::Microsoft::UI::Text::TextConstants>;
    using ITextCharacterFormat = py::winrt_wrapper<winrt::Microsoft::UI::Text::ITextCharacterFormat>;
    using ITextParagraphFormat = py::winrt_wrapper<winrt::Microsoft::UI::Text::ITextParagraphFormat>;
    using ITextRange = py::winrt_wrapper<winrt::Microsoft::UI::Text::ITextRange>;
    using ITextSelection = py::winrt_wrapper<winrt::Microsoft::UI::Text::ITextSelection>;
}

namespace py
{
}
