// WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

#pragma once

#include "pybase.h"
static_assert(winrt::check_version(PYWINRT_VERSION, "0.0.0"), "Mismatched Py/WinRT headers.");
#include <winrt/Windows.Foundation.h>

#include <winrt/Microsoft.Windows.System.Power.h>
#include "py.Microsoft.Windows.System.Power.types.h"


#if __has_include("py.Windows.Foundation.h")
#include "py.Windows.Foundation.h"
#endif

namespace py::impl::Microsoft::Windows::System::Power
{
}

namespace py::wrapper::Microsoft::Windows::System::Power
{
    using PowerManager = py::winrt_wrapper<winrt::Microsoft::Windows::System::Power::PowerManager>;
}

namespace py
{
}
