# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import enum

import winrt.system

_ns_module = winrt.system._import_ns_module("Windows.Management.Workplace")

class MessagingSyncPolicy(enum.IntEnum):
    DISALLOWED = 0
    ALLOWED = 1
    REQUIRED = 2

MdmPolicy = _ns_module.MdmPolicy
WorkplaceSettings = _ns_module.WorkplaceSettings
