# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import enum

import winrt.runtime._internals
import winrt.system
from winrt._winrt_windows_media_audio import (
    _abi_version_,
    _generator_version_,
    AudioDeviceInputNode,
    AudioDeviceOutputNode,
    AudioEffectsPackConfiguration,
    AudioFileInputNode,
    AudioFileOutputNode,
    AudioFrameCompletedEventArgs,
    AudioFrameInputNode,
    AudioFrameOutputNode,
    AudioGraph,
    AudioGraphBatchUpdater,
    AudioGraphConnection,
    AudioGraphSettings,
    AudioGraphUnrecoverableErrorOccurredEventArgs,
    AudioNodeEmitter,
    AudioNodeEmitterConeProperties,
    AudioNodeEmitterDecayModel,
    AudioNodeEmitterNaturalDecayModelProperties,
    AudioNodeEmitterShape,
    AudioNodeListener,
    AudioPlaybackConnection,
    AudioPlaybackConnectionOpenResult,
    AudioStateMonitor,
    AudioSubmixNode,
    CreateAudioDeviceInputNodeResult,
    CreateAudioDeviceOutputNodeResult,
    CreateAudioFileInputNodeResult,
    CreateAudioFileOutputNodeResult,
    CreateAudioGraphResult,
    CreateMediaSourceAudioInputNodeResult,
    EchoEffectDefinition,
    EqualizerBand,
    EqualizerEffectDefinition,
    FrameInputNodeQuantumStartedEventArgs,
    LimiterEffectDefinition,
    MediaSourceAudioInputNode,
    ReverbEffectDefinition,
    SetDefaultSpatialAudioFormatResult,
    SpatialAudioDeviceConfiguration,
    SpatialAudioFormatConfiguration,
    SpatialAudioFormatSubtype,
    _IAudioInputNode,
    IAudioInputNode,
    _IAudioInputNode2,
    IAudioInputNode2,
    _IAudioNode,
    IAudioNode,
    _IAudioNodeWithListener,
    IAudioNodeWithListener,
)

__all__ = [
    "AudioDeviceNodeCreationStatus",
    "AudioEffectsPackStatus",
    "AudioFileNodeCreationStatus",
    "AudioGraphCreationStatus",
    "AudioGraphUnrecoverableError",
    "AudioNodeEmitterDecayKind",
    "AudioNodeEmitterSettings",
    "AudioNodeEmitterShapeKind",
    "AudioPlaybackConnectionOpenResultStatus",
    "AudioPlaybackConnectionState",
    "MediaSourceAudioInputNodeCreationStatus",
    "MixedRealitySpatialAudioFormatPolicy",
    "QuantumSizeSelectionMode",
    "SetDefaultSpatialAudioFormatStatus",
    "SpatialAudioModel",
    "AudioDeviceInputNode",
    "AudioDeviceOutputNode",
    "AudioEffectsPackConfiguration",
    "AudioFileInputNode",
    "AudioFileOutputNode",
    "AudioFrameCompletedEventArgs",
    "AudioFrameInputNode",
    "AudioFrameOutputNode",
    "AudioGraph",
    "AudioGraphBatchUpdater",
    "AudioGraphConnection",
    "AudioGraphSettings",
    "AudioGraphUnrecoverableErrorOccurredEventArgs",
    "AudioNodeEmitter",
    "AudioNodeEmitterConeProperties",
    "AudioNodeEmitterDecayModel",
    "AudioNodeEmitterNaturalDecayModelProperties",
    "AudioNodeEmitterShape",
    "AudioNodeListener",
    "AudioPlaybackConnection",
    "AudioPlaybackConnectionOpenResult",
    "AudioStateMonitor",
    "AudioSubmixNode",
    "CreateAudioDeviceInputNodeResult",
    "CreateAudioDeviceOutputNodeResult",
    "CreateAudioFileInputNodeResult",
    "CreateAudioFileOutputNodeResult",
    "CreateAudioGraphResult",
    "CreateMediaSourceAudioInputNodeResult",
    "EchoEffectDefinition",
    "EqualizerBand",
    "EqualizerEffectDefinition",
    "FrameInputNodeQuantumStartedEventArgs",
    "LimiterEffectDefinition",
    "MediaSourceAudioInputNode",
    "ReverbEffectDefinition",
    "SetDefaultSpatialAudioFormatResult",
    "SpatialAudioDeviceConfiguration",
    "SpatialAudioFormatConfiguration",
    "SpatialAudioFormatSubtype",
    "IAudioInputNode",
    "IAudioInputNode2",
    "IAudioNode",
    "IAudioNodeWithListener",
]

class AudioDeviceNodeCreationStatus(enum.IntEnum):
    SUCCESS = 0
    DEVICE_NOT_AVAILABLE = 1
    FORMAT_NOT_SUPPORTED = 2
    UNKNOWN_FAILURE = 3
    ACCESS_DENIED = 4

class AudioEffectsPackStatus(enum.IntEnum):
    NOT_ENABLED = 0
    ENABLED = 1
    NOT_SUPPORTED = 2

class AudioFileNodeCreationStatus(enum.IntEnum):
    SUCCESS = 0
    FILE_NOT_FOUND = 1
    INVALID_FILE_TYPE = 2
    FORMAT_NOT_SUPPORTED = 3
    UNKNOWN_FAILURE = 4

class AudioGraphCreationStatus(enum.IntEnum):
    SUCCESS = 0
    DEVICE_NOT_AVAILABLE = 1
    FORMAT_NOT_SUPPORTED = 2
    UNKNOWN_FAILURE = 3

class AudioGraphUnrecoverableError(enum.IntEnum):
    NONE = 0
    AUDIO_DEVICE_LOST = 1
    AUDIO_SESSION_DISCONNECTED = 2
    UNKNOWN_FAILURE = 3

class AudioNodeEmitterDecayKind(enum.IntEnum):
    NATURAL = 0
    CUSTOM = 1

class AudioNodeEmitterSettings(enum.IntFlag):
    NONE = 0x0
    DISABLE_DOPPLER = 0x1

class AudioNodeEmitterShapeKind(enum.IntEnum):
    OMNIDIRECTIONAL = 0
    CONE = 1

class AudioPlaybackConnectionOpenResultStatus(enum.IntEnum):
    SUCCESS = 0
    REQUEST_TIMED_OUT = 1
    DENIED_BY_SYSTEM = 2
    UNKNOWN_FAILURE = 3

class AudioPlaybackConnectionState(enum.IntEnum):
    CLOSED = 0
    OPENED = 1

class MediaSourceAudioInputNodeCreationStatus(enum.IntEnum):
    SUCCESS = 0
    FORMAT_NOT_SUPPORTED = 1
    NETWORK_ERROR = 2
    UNKNOWN_FAILURE = 3

class MixedRealitySpatialAudioFormatPolicy(enum.IntEnum):
    USE_MIXED_REALITY_DEFAULT_SPATIAL_AUDIO_FORMAT = 0
    USE_DEVICE_CONFIGURATION_DEFAULT_SPATIAL_AUDIO_FORMAT = 1

class QuantumSizeSelectionMode(enum.IntEnum):
    SYSTEM_DEFAULT = 0
    LOWEST_LATENCY = 1
    CLOSEST_TO_DESIRED = 2

class SetDefaultSpatialAudioFormatStatus(enum.IntEnum):
    SUCCEEDED = 0
    ACCESS_DENIED = 1
    LICENSE_EXPIRED = 2
    LICENSE_NOT_VALID_FOR_AUDIO_ENDPOINT = 3
    NOT_SUPPORTED_ON_AUDIO_ENDPOINT = 4
    UNKNOWN_ERROR = 5

class SpatialAudioModel(enum.IntEnum):
    OBJECT_BASED = 0
    FOLD_DOWN = 1

winrt.runtime._internals.alias_method(AudioDeviceInputNode, "add_outgoing_connection_with_gain", "add_outgoing_connection")
winrt.runtime._internals.alias_method(AudioFileInputNode, "add_outgoing_connection_with_gain", "add_outgoing_connection")
winrt.runtime._internals.alias_method(AudioFrameInputNode, "add_outgoing_connection_with_gain", "add_outgoing_connection")
winrt.runtime._internals.alias_method(AudioGraph, "create_device_input_node_with_format_and_emitter_on_device_async", "create_device_input_node_async")
winrt.runtime._internals.alias_method(AudioGraph, "create_device_input_node_with_format_async", "create_device_input_node_async")
winrt.runtime._internals.alias_method(AudioGraph, "create_device_input_node_with_format_on_device_async", "create_device_input_node_async")
winrt.runtime._internals.alias_method(AudioGraph, "create_file_input_node_with_emitter_async", "create_file_input_node_async")
winrt.runtime._internals.alias_method(AudioGraph, "create_file_output_node_with_file_profile_async", "create_file_output_node_async")
winrt.runtime._internals.alias_method(AudioGraph, "create_frame_input_node_with_format", "create_frame_input_node")
winrt.runtime._internals.alias_method(AudioGraph, "create_frame_input_node_with_format_and_emitter", "create_frame_input_node")
winrt.runtime._internals.alias_method(AudioGraph, "create_frame_output_node_with_format", "create_frame_output_node")
winrt.runtime._internals.alias_method(AudioGraph, "create_media_source_audio_input_node_with_emitter_async", "create_media_source_audio_input_node_async")
winrt.runtime._internals.alias_method(AudioGraph, "create_submix_node_with_format", "create_submix_node")
winrt.runtime._internals.alias_method(AudioGraph, "create_submix_node_with_format_and_emitter", "create_submix_node")
winrt.runtime._internals.alias_static_method(AudioStateMonitor, "create_for_capture_monitoring_with_category", "create_for_capture_monitoring")
winrt.runtime._internals.alias_static_method(AudioStateMonitor, "create_for_capture_monitoring_with_category_and_device_role", "create_for_capture_monitoring")
winrt.runtime._internals.alias_static_method(AudioStateMonitor, "create_for_render_monitoring_with_category", "create_for_render_monitoring")
winrt.runtime._internals.alias_static_method(AudioStateMonitor, "create_for_render_monitoring_with_category_and_device_role", "create_for_render_monitoring")
winrt.runtime._internals.alias_method(AudioSubmixNode, "add_outgoing_connection_with_gain", "add_outgoing_connection")
winrt.runtime._internals.alias_method(MediaSourceAudioInputNode, "add_outgoing_connection_with_gain", "add_outgoing_connection")
winrt.runtime._internals.alias_method(_IAudioInputNode, "add_outgoing_connection_with_gain", "add_outgoing_connection")
winrt.runtime._internals.alias_method(_IAudioInputNode2, "add_outgoing_connection_with_gain", "add_outgoing_connection")
