# WARNING: Please don't edit this file. It was generated by Python/WinRT v2.0.0-beta.2

import enum

import winrt.system
from winrt import _winrt_windows_applicationmodel_userdataaccounts_systemaccess

__all__ = [
    "DeviceAccountAuthenticationType",
    "DeviceAccountIconId",
    "DeviceAccountMailAgeFilter",
    "DeviceAccountServerType",
    "DeviceAccountSyncScheduleKind",
    "DeviceAccountConfiguration",
    "UserDataAccountSystemAccessManager",
]

class DeviceAccountAuthenticationType(enum.IntEnum):
    BASIC = 0
    O_AUTH = 1
    SINGLE_SIGN_ON = 2

class DeviceAccountIconId(enum.IntEnum):
    EXCHANGE = 0
    MSA = 1
    OUTLOOK = 2
    GENERIC = 3

class DeviceAccountMailAgeFilter(enum.IntEnum):
    ALL = 0
    LAST1_DAY = 1
    LAST3_DAYS = 2
    LAST7_DAYS = 3
    LAST14_DAYS = 4
    LAST30_DAYS = 5
    LAST90_DAYS = 6

class DeviceAccountServerType(enum.IntEnum):
    EXCHANGE = 0
    POP = 1
    IMAP = 2

class DeviceAccountSyncScheduleKind(enum.IntEnum):
    MANUAL = 0
    EVERY15_MINUTES = 1
    EVERY30_MINUTES = 2
    EVERY60_MINUTES = 3
    EVERY2_HOURS = 4
    DAILY = 5
    AS_ITEMS_ARRIVE = 6

DeviceAccountConfiguration = _winrt_windows_applicationmodel_userdataaccounts_systemaccess.DeviceAccountConfiguration
UserDataAccountSystemAccessManager = _winrt_windows_applicationmodel_userdataaccounts_systemaccess.UserDataAccountSystemAccessManager
