# WARNING: Please don't edit this file. It was generated by Python/WinRT v0.0.0

import winrt.runtime._internals
import winrt.system
from winrt._winrt_windows_perception_spatial_preview import (
    _abi_version_,
    _generator_version_,
    SpatialGraphInteropFrameOfReferencePreview,
    SpatialGraphInteropPreview,
)

__all__ = [
    "SpatialGraphInteropFrameOfReferencePreview",
    "SpatialGraphInteropPreview",
]

winrt.runtime._internals.alias_static_method(SpatialGraphInteropPreview, "create_coordinate_system_for_node_with_position", "create_coordinate_system_for_node")
winrt.runtime._internals.alias_static_method(SpatialGraphInteropPreview, "create_coordinate_system_for_node_with_position_and_orientation", "create_coordinate_system_for_node")
winrt.runtime._internals.alias_static_method(SpatialGraphInteropPreview, "try_create_frame_of_reference_with_position", "try_create_frame_of_reference")
winrt.runtime._internals.alias_static_method(SpatialGraphInteropPreview, "try_create_frame_of_reference_with_position_and_orientation", "try_create_frame_of_reference")
