# WARNING: Please don't edit this file. It was generated by Python/WinRT v3.2.1

import enum

import winrt.system
from winrt._winrt_windows_web_http_diagnostics import (
    HttpDiagnosticProvider,
    HttpDiagnosticProviderRequestResponseCompletedEventArgs,
    HttpDiagnosticProviderRequestResponseTimestamps,
    HttpDiagnosticProviderRequestSentEventArgs,
    HttpDiagnosticProviderResponseReceivedEventArgs,
    HttpDiagnosticSourceLocation,
)

__all__ = [
    "HttpDiagnosticRequestInitiator",
    "HttpDiagnosticProvider",
    "HttpDiagnosticProviderRequestResponseCompletedEventArgs",
    "HttpDiagnosticProviderRequestResponseTimestamps",
    "HttpDiagnosticProviderRequestSentEventArgs",
    "HttpDiagnosticProviderResponseReceivedEventArgs",
    "HttpDiagnosticSourceLocation",
]

class HttpDiagnosticRequestInitiator(enum.IntEnum):
    PARSED_ELEMENT = 0
    SCRIPT = 1
    IMAGE = 2
    LINK = 3
    STYLE = 4
    XML_HTTP_REQUEST = 5
    MEDIA = 6
    HTML_DOWNLOAD = 7
    PREFETCH = 8
    OTHER = 9
    CROSS_ORIGIN_PRE_FLIGHT = 10
    FETCH = 11
    BEACON = 12

