name: generate
concurrency:
  group: generate-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - .github/workflows/generate.yaml
      - projection/winrt-sdk/src/winrt_sdk/cppwinrt/**
      - projection/winrt-sdk/src/winrt_sdk/pywinrt/**
      - projection/winrt-*/winrt/**/__init__.py
      - projection/winrt-*/winrt/_winrt_*.pyi
      - projection/winrt-*/py.*.cpp
      - projection/winrt-*/pyproject.toml
      - projection/winrt-*/README.md
      - projection/winrt-*/requirements.txt
      - projection/winrt-*/setup.py
      - PyWinRT/**
      - scripts/fetch-tools.ps1
      - scripts/generate-cppwinrt.py
      - scripts/generate-pywinrt.py
      - scripts/generate-pyproject.py

jobs:
  generate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet build PyWinRT -c Release
      - run: ./scripts/fetch-tools.ps1 -noPyWinRT
      - run: python3 ./scripts/generate-cppwinrt.py
      - run: python3 ./scripts/generate-pywinrt.py
      - run: python3 ./scripts/generate-pyproject.py
      # fail if there are changes
      - run: git diff --exit-code
