name: generate
concurrency:
  group: generate-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - .github/workflows/generate.yaml
      - projection/**
      - '!projection/interop/**'
      - '!projection/winrt-runtime/**'
      - PyWinRT/**
      - scripts/fetch-tools.ps1
      - scripts/generate-cppwinrt.py
      - scripts/generate-pywinrt.py
      - scripts/generate-pyproject.py

jobs:
  generate:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
      - run: dotnet build PyWinRT -c Release
      - run: ./scripts/fetch-tools.ps1
      - run: python3 ./scripts/generate-cppwinrt.py
      - run: python3 ./scripts/generate-pywinrt.py
      - run: python3 ./scripts/generate-pyproject.py
      # fail if there are changes
      - run: git diff --exit-code
