name: wheels
concurrency: wheels-${{ github.ref }}
on:
  push:
      tags: [wheels/*]
  # allows compile testing all packages on a branch before merging
  workflow_dispatch:

jobs:
  sdist:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-sdist.txt
      - name: Build winrt-sdk
        run: pyproject-build --outdir wheelhouse projection/winrt-sdk
      - name: Install winrt-sdk
        run: |
          $whl = (Get-ChildItem wheelhouse/winrt_sdk-*.whl | Select-Object -First 1).FullName
          pip install --no-deps $whl
      - name: Build winrt-Microsoft.UI.Xaml
        run: pyproject-build --outdir wheelhouse projection/winrt-Microsoft.UI.Xaml
      - name: Install winrt-Microsoft.UI.Xaml
        run: |
          $whl = (Get-ChildItem wheelhouse/winrt_microsoft_ui_xaml-*.whl | Select-Object -First 1).FullName
          pip install --no-deps $whl
      - name: Build winrt-WindowsAppSDK
        run: pyproject-build --outdir wheelhouse projection/winrt-WindowsAppSDK
      - name: Install winrt-WindowsAppSDK
        run: |
          $whl = (Get-ChildItem wheelhouse/winrt_WindowsAppSDK-*.whl | Select-Object -First 1).FullName
          pip install --no-deps $whl
      - name: Build sdists
        run: python scripts/build-sdist.py
      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sdist_${{ github.run_id }}
          path: wheelhouse/
  bdist:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        py:
          - cp311
          - cp312
          - cp313
          - cp314
          - cp315
        arch:
          - win_amd64
          - win32
          - win_arm64
    steps:
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.12'
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: install nuget packages
        run: ./scripts/fetch-tools.ps1 -noCppWinRT -noWindowsSDK -noMicrosoftUiXaml -noTestWinRT
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-bdist.txt
      - name: Build bdist wheels
        run: python scripts/build-bdist.py --only ${{ matrix.py }}-${{ matrix.arch }}
      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bdist_${{ matrix.py }}-${{ matrix.arch }}_${{ github.run_id }}
          path: wheelhouse/
  publish:
    needs: [sdist, bdist]
    # only publish tagged releases, not manually triggered compile tests
    if: startsWith(github.ref, 'refs/tags/wheels/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist
          pattern: "[bs]dist_*"
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
